#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lexer.h"
// #include "driver.h"

int main(int argc, char *argv[]){
	if(argc!=3){
		printf("Invalid Arguements.\n");
		return 1;
	}
	FILE *fp = fopen(argv[1],"r");

	int opt;
	while(1){
		printf("\n---------------------------------------------------\n");
		printf("Press a number to choose the corresponding option\n");
		// printf("Press 1 to see comment free code\n");
		printf("Press 1 for making the comment free code.\n");
		printf("Press 2 for printing the token list generated by the lexer\n");
		printf("Press 3 for printing the parse tree and errors.\n");
		printf("Press 4 for printing the total time taken\n");
		printf("Press 0 to exit!\n");
		printf("---------------------------------------------------\n");

		scanf("%d", &opt);
		switch(opt){
			case 0:
				printf("\n\nEXITING...\n");
				return 0;
			case 1:
				removeComments(argv[1], argv[2]);	// remove comments.
				printf("Comment free code done.\n");
				break;
			case 2:
			{
				while(1){
					tokenInfo *tk = getNextToken(fp);
					if(tk==NULL)
						continue;
					printf("TOKEN: '%s' VALUE: '%s'  LINENO.: %llu\n", tokenArray[tk->tid], tk->name, tk->lineNo);
					if(tk->tid==TK_DOLLAR)
						break;
				}
				// printf("\n");
			}
		}
	}
	return 0;
}